export interface PositionSkillsReference {
  [position: string]: {
    skills: {
      required: string[]
      preferred: string[]
      bonus: string[]
    }
    experience: {
      keywords: string[]
      roles: string[]
      industries: string[]
    }
    training: {
      certifications: string[]
      courses: string[]
      workshops: string[]
    }
    education: {
      preferred: string[]
      relevant: string[]
    }
    personality: {
      traits: string[]
      keywords: string[]
    }
  }
}

export interface WeightedCriteria {
  education: {
    [degree: string]: number
  }
  experience: {
    [years: string]: number
  }
  skills: {
    required: number
    preferred: number
    bonus: number
  }
  certifications: {
    [certification: string]: number
  }
}

export const POSITION_SKILLS_REFERENCE: PositionSkillsReference = {
  "kitchen-helper": {
    skills: {
      required: [
        "food preparation",
        "food prep",
        "knife skills",
        "basic cooking",
        "food safety",
        "sanitation",
        "cleaning",
        "dishwashing",
        "kitchen equipment",
        "food handling",
        "prep work",
        "chopping",
        "slicing",
        "dicing",
        "washing dishes",
        "kitchen maintenance",
        "food storage",
        "temperature control",
        "portion control",
        "recipe following",
        "kitchen organization",
        "inventory management",
        "stock rotation",
        "FIFO",
        "allergen awareness",
        "cross contamination prevention",
        "food labeling",
        "equipment cleaning",
        "deep cleaning",
        "sanitizing",
        "food waste management",
        "ingredient preparation",
        "vegetable prep",
        "meat preparation",
        "sauce making",
        "soup preparation",
        "salad preparation",
        "garnishing",
        "plating basics",
        "kitchen safety",
        "burn prevention",
        "cut prevention",
        "slip prevention",
      ],
      preferred: [
        "menu knowledge",
        "cooking techniques",
        "baking basics",
        "sauce preparation",
        "grilling",
        "sautéing",
        "roasting",
        "steaming",
        "blanching",
        "braising",
        "frying",
        "poaching",
        "marinating",
        "seasoning",
        "spice knowledge",
        "herb knowledge",
        "flavor pairing",
        "texture understanding",
        "cooking times",
        "doneness testing",
        "food presentation",
        "garnish techniques",
        "knife maintenance",
        "equipment maintenance",
        "inventory tracking",
        "cost control",
        "waste reduction",
        "efficiency optimization",
        "time management",
        "multitasking",
        "priority setting",
        "workflow organization",
        "team coordination",
      ],
      bonus: [
        "culinary school",
        "chef training",
        "line cook experience",
        "catering experience",
        "restaurant experience",
        "commercial kitchen",
        "food service",
        "hospitality",
        "fine dining",
        "fast casual",
        "quick service",
        "buffet service",
        "banquet service",
        "institutional cooking",
        "healthcare food service",
        "school food service",
        "corporate catering",
        "event catering",
        "wedding catering",
        "specialty diets",
        "vegan cooking",
        "vegetarian cooking",
        "gluten-free preparation",
        "allergen-free cooking",
        "international cuisine",
        "ethnic cooking",
        "regional specialties",
        "farm-to-table",
        "organic food preparation",
        "sustainable practices",
        "local sourcing",
      ],
    },
    experience: {
      keywords: [
        "kitchen",
        "restaurant",
        "food service",
        "culinary",
        "prep cook",
        "line cook",
        "dishwasher",
        "food preparation",
        "catering",
        "cafeteria",
        "dining",
        "hospitality",
        "commercial kitchen",
        "institutional kitchen",
        "hotel kitchen",
        "resort kitchen",
        "cruise ship kitchen",
        "hospital kitchen",
        "school kitchen",
        "corporate kitchen",
        "banquet kitchen",
        "fast food",
        "quick service",
        "fine dining",
        "casual dining",
        "buffet",
        "deli",
        "bakery",
        "pastry shop",
        "coffee shop",
        "café",
        "bistro",
        "tavern",
        "pub",
        "food truck",
        "catering company",
        "event venue",
        "country club",
        "retirement home",
      ],
      roles: [
        "kitchen helper",
        "prep cook",
        "line cook",
        "dishwasher",
        "food service worker",
        "kitchen assistant",
        "culinary assistant",
        "restaurant worker",
        "catering assistant",
        "food prep worker",
        "kitchen staff",
        "back of house",
        "BOH",
        "kitchen crew",
        "food handler",
        "kitchen attendant",
        "culinary aide",
        "cooking assistant",
        "food production worker",
        "kitchen technician",
        "dietary aide",
        "nutrition assistant",
      ],
      industries: [
        "restaurant",
        "hospitality",
        "food service",
        "catering",
        "hotel",
        "resort",
        "healthcare",
        "education",
        "corporate dining",
        "institutional food service",
        "cruise line",
        "airline catering",
        "sports venue",
        "entertainment venue",
        "theme park",
        "casino",
        "country club",
        "retirement community",
        "assisted living",
      ],
    },
    training: {
      certifications: [
        "ServSafe",
        "food safety certification",
        "HACCP",
        "allergen training",
        "sanitation certification",
        "food handler's license",
        "food manager certification",
        "safe food handling",
        "food protection",
        "culinary arts certificate",
        "food service management",
        "nutrition certification",
        "dietary management",
        "kitchen safety training",
        "knife skills certification",
        "equipment operation training",
        "first aid",
        "CPR",
        "workplace safety",
      ],
      courses: [
        "culinary arts",
        "food preparation",
        "kitchen management",
        "food safety",
        "nutrition",
        "dietary planning",
        "menu planning",
        "cost control",
        "inventory management",
        "food service operations",
        "hospitality management",
        "restaurant management",
        "cooking fundamentals",
        "baking fundamentals",
        "knife skills",
        "food presentation",
      ],
      workshops: [
        "knife skills workshop",
        "food safety workshop",
        "cooking techniques workshop",
        "menu development workshop",
        "cost control workshop",
        "efficiency workshop",
        "team building workshop",
        "customer service workshop",
        "leadership workshop",
      ],
    },
    education: {
      preferred: [
        "culinary arts",
        "food service",
        "hospitality management",
        "nutrition",
        "dietetics",
        "food science",
        "restaurant management",
        "hotel management",
        "business administration",
      ],
      relevant: [
        "culinary school",
        "community college culinary program",
        "vocational cooking program",
        "food service training program",
        "hospitality degree",
        "business degree",
      ],
    },
    personality: {
      traits: [
        "detail-oriented",
        "organized",
        "efficient",
        "reliable",
        "punctual",
        "hardworking",
        "team player",
        "collaborative",
        "adaptable",
        "flexible",
        "patient",
        "calm under pressure",
        "multitasking",
        "time management",
        "problem-solving",
        "creative",
        "innovative",
        "quality-focused",
        "safety-conscious",
        "hygiene-focused",
        "professional",
        "respectful",
      ],
      keywords: [
        "attention to detail",
        "organizational skills",
        "time management",
        "work ethic",
        "team collaboration",
        "communication skills",
        "problem solving",
        "adaptability",
        "reliability",
        "punctuality",
        "efficiency",
        "quality focus",
        "safety awareness",
        "cleanliness",
        "professionalism",
        "positive attitude",
        "learning mindset",
      ],
    },
  },

  "server-waiter": {
    skills: {
      required: [
        "customer service",
        "order taking",
        "food service",
        "table service",
        "menu knowledge",
        "POS system",
        "cash handling",
        "payment processing",
        "multitasking",
        "communication",
        "active listening",
        "problem solving",
        "conflict resolution",
        "time management",
        "memory skills",
        "attention to detail",
        "upselling",
        "suggestive selling",
        "wine knowledge",
        "beverage service",
        "food safety",
        "hygiene",
        "cleanliness",
        "table setting",
        "silverware knowledge",
        "glassware handling",
        "tray carrying",
      ],
      preferred: [
        "wine pairing",
        "cocktail knowledge",
        "beer knowledge",
        "specialty drinks",
        "dietary restrictions",
        "allergen awareness",
        "fine dining service",
        "formal service",
        "banquet service",
        "event service",
        "catering service",
        "buffet service",
        "room service",
        "bar service",
        "coffee service",
        "tea service",
        "dessert service",
        "cheese service",
        "bread service",
        "tableside service",
        "flambé service",
        "carving service",
        "presentation skills",
        "sales techniques",
        "customer retention",
        "loyalty building",
        "complaint handling",
      ],
      bonus: [
        "sommelier training",
        "bartending",
        "mixology",
        "coffee expertise",
        "tea expertise",
        "food and wine pairing",
        "international cuisine knowledge",
        "cultural dining etiquette",
        "multiple languages",
        "bilingual",
        "trilingual",
        "hospitality management",
        "restaurant management",
        "training experience",
        "mentoring",
        "leadership",
        "event planning",
        "catering coordination",
        "special events",
        "private dining",
      ],
    },
    experience: {
      keywords: [
        "server",
        "waiter",
        "waitress",
        "food service",
        "restaurant",
        "dining",
        "hospitality",
        "customer service",
        "table service",
        "fine dining",
        "casual dining",
        "fast casual",
        "banquet",
        "catering",
        "event service",
        "room service",
        "bar service",
        "cocktail service",
        "wine service",
        "coffee service",
        "breakfast service",
        "lunch service",
        "dinner service",
        "brunch service",
        "buffet service",
        "à la carte",
        "prix fixe",
        "tasting menu",
      ],
      roles: [
        "server",
        "waiter",
        "waitress",
        "food server",
        "dining room server",
        "banquet server",
        "cocktail server",
        "wine server",
        "room service attendant",
        "catering server",
        "event server",
        "fine dining server",
        "casual dining server",
        "restaurant server",
        "hospitality associate",
        "guest services",
        "dining services",
        "food and beverage server",
      ],
      industries: [
        "restaurant",
        "fine dining",
        "casual dining",
        "fast casual",
        "hotel",
        "resort",
        "cruise ship",
        "country club",
        "private club",
        "banquet hall",
        "event venue",
        "catering company",
        "conference center",
        "convention center",
        "casino",
        "sports venue",
        "entertainment venue",
        "theme park",
        "airport dining",
        "corporate dining",
      ],
    },
    training: {
      certifications: [
        "food safety certification",
        "alcohol service certification",
        "responsible beverage service",
        "TIPS certification",
        "ServSafe",
        "allergen training",
        "wine certification",
        "sommelier certification",
        "bartending certification",
        "customer service certification",
        "hospitality certification",
        "conflict resolution training",
        "sales training",
      ],
      courses: [
        "hospitality management",
        "food and beverage service",
        "wine studies",
        "customer service",
        "sales techniques",
        "communication skills",
        "conflict resolution",
        "cultural awareness",
        "restaurant operations",
        "dining room management",
        "event service",
        "banquet service",
      ],
      workshops: [
        "wine tasting workshop",
        "customer service workshop",
        "sales training workshop",
        "communication workshop",
        "cultural sensitivity workshop",
        "team building workshop",
        "leadership workshop",
        "conflict resolution workshop",
        "upselling workshop",
      ],
    },
    education: {
      preferred: [
        "hospitality management",
        "restaurant management",
        "business administration",
        "communications",
        "marketing",
        "culinary arts",
        "food and beverage management",
        "event management",
        "tourism",
        "international business",
        "foreign languages",
        "cultural studies",
      ],
      relevant: [
        "hospitality degree",
        "business degree",
        "communications degree",
        "culinary degree",
        "tourism degree",
        "language degree",
        "customer service training",
        "sales training",
      ],
    },
    personality: {
      traits: [
        "outgoing",
        "friendly",
        "personable",
        "charismatic",
        "energetic",
        "enthusiastic",
        "patient",
        "empathetic",
        "understanding",
        "diplomatic",
        "tactful",
        "professional",
        "confident",
        "articulate",
        "persuasive",
        "attentive",
        "observant",
        "proactive",
        "solution-oriented",
        "team-oriented",
        "customer-focused",
        "detail-oriented",
      ],
      keywords: [
        "people skills",
        "interpersonal skills",
        "communication skills",
        "social skills",
        "customer focus",
        "service orientation",
        "positive attitude",
        "professional demeanor",
        "emotional intelligence",
        "cultural sensitivity",
        "adaptability",
        "flexibility",
        "stress management",
        "grace under pressure",
        "multitasking ability",
        "memory skills",
      ],
    },
  },

  "house-keeping": {
    skills: {
      required: [
        "cleaning",
        "sanitizing",
        "disinfecting",
        "vacuuming",
        "mopping",
        "dusting",
        "polishing",
        "bed making",
        "laundry",
        "ironing",
        "folding",
        "organizing",
        "restocking",
        "inventory",
        "supply management",
        "equipment operation",
        "safety procedures",
        "chemical handling",
        "time management",
        "attention to detail",
        "quality control",
        "room inspection",
        "maintenance reporting",
        "guest service",
        "privacy respect",
        "confidentiality",
      ],
      preferred: [
        "deep cleaning",
        "carpet cleaning",
        "upholstery cleaning",
        "window cleaning",
        "floor care",
        "bathroom sanitization",
        "kitchen cleaning",
        "appliance cleaning",
        "furniture care",
        "fabric care",
        "stain removal",
        "odor elimination",
        "air freshening",
        "decoration arrangement",
        "plant care",
        "pet area cleaning",
        "outdoor cleaning",
        "garage cleaning",
        "basement cleaning",
        "attic cleaning",
        "storage organization",
        "closet organization",
        "seasonal cleaning",
      ],
      bonus: [
        "eco-friendly cleaning",
        "green cleaning products",
        "organic cleaning",
        "allergen-free cleaning",
        "specialized cleaning",
        "antique care",
        "artwork care",
        "electronics cleaning",
        "medical equipment cleaning",
        "industrial cleaning",
        "commercial cleaning",
        "hospitality cleaning",
        "luxury home cleaning",
        "estate management",
        "concierge services",
        "personal assistance",
        "event preparation",
        "party cleanup",
        "move-in cleaning",
        "move-out cleaning",
      ],
    },
    experience: {
      keywords: [
        "housekeeping",
        "cleaning",
        "janitorial",
        "custodial",
        "maintenance",
        "sanitation",
        "hospitality",
        "hotel",
        "resort",
        "residential",
        "commercial",
        "office cleaning",
        "medical cleaning",
        "industrial cleaning",
        "institutional cleaning",
        "facility maintenance",
        "property management",
        "estate management",
        "domestic service",
        "home care",
      ],
      roles: [
        "housekeeper",
        "cleaner",
        "janitor",
        "custodian",
        "maintenance worker",
        "cleaning technician",
        "housekeeping attendant",
        "room attendant",
        "facility cleaner",
        "office cleaner",
        "residential cleaner",
        "commercial cleaner",
        "hospital cleaner",
        "school cleaner",
        "hotel housekeeper",
        "resort housekeeper",
        "private housekeeper",
        "estate manager",
      ],
      industries: [
        "hospitality",
        "hotel",
        "resort",
        "healthcare",
        "medical",
        "office",
        "commercial",
        "residential",
        "institutional",
        "educational",
        "government",
        "retail",
        "industrial",
        "property management",
        "facility management",
        "cleaning services",
        "domestic services",
      ],
    },
    training: {
      certifications: [
        "cleaning certification",
        "sanitation certification",
        "chemical safety training",
        "OSHA safety training",
        "infection control training",
        "bloodborne pathogen training",
        "hazmat training",
        "equipment operation certification",
        "green cleaning certification",
        "hospitality certification",
        "customer service certification",
        "first aid",
        "CPR",
      ],
      courses: [
        "housekeeping management",
        "cleaning techniques",
        "chemical safety",
        "equipment operation",
        "customer service",
        "hospitality operations",
        "facility management",
        "property management",
        "infection control",
        "safety procedures",
        "quality control",
        "inventory management",
      ],
      workshops: [
        "cleaning techniques workshop",
        "chemical safety workshop",
        "equipment training workshop",
        "customer service workshop",
        "time management workshop",
        "quality control workshop",
        "safety training workshop",
        "green cleaning workshop",
        "efficiency workshop",
      ],
    },
    education: {
      preferred: [
        "hospitality management",
        "facility management",
        "property management",
        "business administration",
        "environmental science",
        "chemistry",
        "health sciences",
        "public health",
        "safety management",
      ],
      relevant: [
        "housekeeping certificate",
        "cleaning certification",
        "facility management degree",
        "hospitality degree",
        "business degree",
        "safety certification",
        "health certification",
      ],
    },
    personality: {
      traits: [
        "nature-loving",
        "outdoorsy",
        "patient",
        "observant",
        "detail-oriented",
        "nurturing",
        "caring",
        "responsible",
        "reliable",
        "hardworking",
        "physical",
        "strong",
        "enduring",
        "weather-tolerant",
        "seasonal-aware",
        "environmentally conscious",
        "sustainable-minded",
        "creative",
        "artistic",
        "aesthetic-minded",
        "problem-solving",
        "adaptable",
        "flexible",
      ],
      keywords: [
        "love of nature",
        "outdoor enthusiasm",
        "patience",
        "observation skills",
        "attention to detail",
        "nurturing nature",
        "caring attitude",
        "responsibility",
        "reliability",
        "work ethic",
        "physical fitness",
        "strength",
        "endurance",
        "weather tolerance",
        "seasonal awareness",
        "environmental consciousness",
        "sustainability mindset",
        "creativity",
        "artistic sense",
        "aesthetic appreciation",
        "problem solving",
        "adaptability",
        "flexibility",
      ],
    },
  },

  cashier: {
    skills: {
      required: [
        "cash handling",
        "POS system",
        "payment processing",
        "credit card processing",
        "change calculation",
        "money counting",
        "register operation",
        "receipt printing",
        "transaction recording",
        "customer service",
        "communication",
        "active listening",
        "problem solving",
        "multitasking",
        "attention to detail",
        "accuracy",
        "speed",
        "efficiency",
        "math skills",
        "basic accounting",
        "inventory tracking",
        "product knowledge",
        "barcode scanning",
        "price checking",
      ],
      preferred: [
        "upselling",
        "cross-selling",
        "suggestive selling",
        "customer retention",
        "loyalty programs",
        "promotional knowledge",
        "discount application",
        "coupon processing",
        "return processing",
        "exchange processing",
        "refund processing",
        "gift card processing",
        "layaway processing",
        "special orders",
        "customer accounts",
        "credit applications",
        "warranty sales",
        "service plans",
        "delivery coordination",
        "pickup coordination",
        "inventory management",
      ],
      bonus: [
        "multiple languages",
        "bilingual",
        "trilingual",
        "management experience",
        "training experience",
        "supervisory experience",
        "team leadership",
        "shift management",
        "opening procedures",
        "closing procedures",
        "cash reconciliation",
        "deposit preparation",
        "loss prevention",
        "security awareness",
        "fraud detection",
        "counterfeit detection",
        "theft prevention",
        "emergency procedures",
        "conflict resolution",
        "complaint handling",
        "escalation procedures",
      ],
    },
    experience: {
      keywords: [
        "cashier",
        "retail",
        "sales",
        "customer service",
        "cash handling",
        "POS",
        "register",
        "checkout",
        "front end",
        "customer facing",
        "transaction processing",
        "payment processing",
        "money handling",
        "financial transactions",
        "retail sales",
        "store operations",
        "customer relations",
        "guest services",
        "point of sale",
        "merchandise",
        "inventory",
      ],
      roles: [
        "cashier",
        "sales associate",
        "retail associate",
        "customer service representative",
        "front end associate",
        "checkout operator",
        "register operator",
        "sales clerk",
        "store clerk",
        "retail clerk",
        "customer service clerk",
        "transaction processor",
        "payment processor",
        "guest services associate",
        "customer relations associate",
      ],
      industries: [
        "retail",
        "grocery",
        "supermarket",
        "department store",
        "specialty retail",
        "convenience store",
        "gas station",
        "pharmacy",
        "restaurant",
        "fast food",
        "quick service",
        "hospitality",
        "entertainment",
        "sports venue",
        "theme park",
        "movie theater",
        "automotive",
        "hardware",
      ],
    },
    training: {
      certifications: [
        "cash handling certification",
        "POS system certification",
        "customer service certification",
        "sales training certification",
        "loss prevention certification",
        "security training",
        "fraud prevention training",
        "money handling certification",
        "retail certification",
        "payment processing certification",
        "credit card processing certification",
      ],
      courses: [
        "retail operations",
        "customer service",
        "sales techniques",
        "cash management",
        "inventory management",
        "loss prevention",
        "security procedures",
        "communication skills",
        "conflict resolution",
        "product knowledge",
        "merchandising",
        "retail math",
      ],
      workshops: [
        "customer service workshop",
        "sales training workshop",
        "cash handling workshop",
        "communication workshop",
        "conflict resolution workshop",
        "upselling workshop",
        "product knowledge workshop",
        "security awareness workshop",
        "fraud prevention workshop",
      ],
    },
    education: {
      preferred: [
        "business administration",
        "retail management",
        "marketing",
        "communications",
        "accounting",
        "finance",
        "mathematics",
        "economics",
        "hospitality management",
        "customer service",
      ],
      relevant: [
        "business degree",
        "retail certification",
        "customer service training",
        "sales training",
        "accounting certification",
        "finance certification",
        "mathematics education",
      ],
    },
    personality: {
      traits: [
        "honest",
        "trustworthy",
        "reliable",
        "accurate",
        "detail-oriented",
        "patient",
        "friendly",
        "helpful",
        "courteous",
        "professional",
        "efficient",
        "organized",
        "responsible",
        "dependable",
        "punctual",
        "calm under pressure",
        "good with numbers",
        "people-oriented",
        "service-minded",
        "positive attitude",
        "team player",
        "adaptable",
        "flexible",
      ],
      keywords: [
        "honesty",
        "integrity",
        "reliability",
        "accuracy",
        "attention to detail",
        "patience",
        "friendliness",
        "helpfulness",
        "courtesy",
        "professionalism",
        "efficiency",
        "organization",
        "responsibility",
        "dependability",
        "punctuality",
        "stress management",
        "numerical skills",
        "people skills",
        "service orientation",
        "positive attitude",
        "teamwork",
        "adaptability",
      ],
    },
  },

  barista: {
    skills: {
      required: [
        "coffee preparation",
        "espresso making",
        "latte art",
        "milk steaming",
        "coffee grinding",
        "brewing techniques",
        "coffee knowledge",
        "equipment operation",
        "machine maintenance",
        "customer service",
        "order taking",
        "POS system",
        "cash handling",
        "multitasking",
        "time management",
        "quality control",
        "consistency",
        "cleanliness",
        "sanitation",
        "inventory management",
        "stock rotation",
        "product knowledge",
        "menu knowledge",
      ],
      preferred: [
        "specialty drinks",
        "seasonal drinks",
        "custom drinks",
        "alternative milk",
        "dietary accommodations",
        "coffee roasting",
        "bean selection",
        "origin knowledge",
        "flavor profiles",
        "tasting notes",
        "brewing methods",
        "pour over",
        "French press",
        "cold brew",
        "nitro coffee",
        "tea preparation",
        "pastry knowledge",
        "food pairing",
        "upselling",
        "customer education",
        "coffee culture",
        "third wave coffee",
        "artisan techniques",
        "presentation skills",
        "social media",
      ],
      bonus: [
        "coffee competition",
        "barista championship",
        "latte art competition",
        "coffee judging",
        "coffee cupping",
        "sensory evaluation",
        "coffee education",
        "training others",
        "mentoring",
        "shift supervision",
        "opening procedures",
        "closing procedures",
        "inventory ordering",
        "vendor relations",
        "equipment troubleshooting",
        "recipe development",
        "menu development",
        "marketing",
        "social media management",
        "event planning",
        "coffee events",
        "workshops",
      ],
    },
    experience: {
      keywords: [
        "barista",
        "coffee",
        "espresso",
        "café",
        "coffee shop",
        "specialty coffee",
        "third wave coffee",
        "artisan coffee",
        "coffee house",
        "coffee bar",
        "coffee roastery",
        "coffee chain",
        "independent coffee",
        "local coffee",
        "coffee culture",
        "coffee service",
        "beverage service",
        "hospitality",
        "customer service",
        "food service",
        "quick service",
        "counter service",
      ],
      roles: [
        "barista",
        "coffee specialist",
        "espresso technician",
        "coffee artist",
        "beverage specialist",
        "café associate",
        "coffee shop worker",
        "coffee server",
        "drink maker",
        "coffee preparer",
        "shift supervisor",
        "coffee trainer",
        "head barista",
        "lead barista",
        "coffee consultant",
      ],
      industries: [
        "coffee shop",
        "café",
        "specialty coffee",
        "coffee roastery",
        "coffee chain",
        "independent coffee",
        "hotel coffee bar",
        "restaurant coffee service",
        "corporate coffee service",
        "catering",
        "food service",
        "hospitality",
        "retail coffee",
        "grocery coffee bar",
        "bookstore café",
      ],
    },
    training: {
      certifications: [
        "barista certification",
        "coffee certification",
        "espresso certification",
        "latte art certification",
        "coffee judging certification",
        "cupping certification",
        "roasting certification",
        "coffee education certification",
        "specialty coffee certification",
        "food safety certification",
        "customer service certification",
        "equipment certification",
        "machine operation certification",
      ],
      courses: [
        "coffee studies",
        "barista training",
        "espresso training",
        "latte art training",
        "coffee roasting",
        "coffee cupping",
        "sensory evaluation",
        "coffee business",
        "café management",
        "customer service",
        "hospitality management",
        "food service",
        "beverage management",
        "quality control",
      ],
      workshops: [
        "latte art workshop",
        "coffee cupping workshop",
        "brewing workshop",
        "espresso workshop",
        "coffee education workshop",
        "customer service workshop",
        "coffee competition workshop",
        "roasting workshop",
        "coffee business workshop",
        "café management workshop",
      ],
    },
    education: {
      preferred: [
        "hospitality management",
        "culinary arts",
        "food science",
        "business administration",
        "marketing",
        "communications",
        "customer service",
        "food and beverage management",
        "restaurant management",
        "retail management",
        "coffee studies",
        "beverage studies",
      ],
      relevant: [
        "barista certification",
        "coffee certification",
        "hospitality degree",
        "culinary degree",
        "business degree",
        "food service certification",
        "customer service training",
      ],
    },
    personality: {
      traits: [
        "passionate",
        "enthusiastic",
        "creative",
        "artistic",
        "detail-oriented",
        "perfectionist",
        "friendly",
        "outgoing",
        "energetic",
        "patient",
        "helpful",
        "knowledgeable",
        "curious",
        "learning-oriented",
        "quality-focused",
        "customer-focused",
        "team-oriented",
        "adaptable",
        "flexible",
        "efficient",
        "organized",
        "reliable",
        "professional",
        "positive",
      ],
      keywords: [
        "passion for coffee",
        "enthusiasm",
        "creativity",
        "artistry",
        "attention to detail",
        "perfectionism",
        "friendliness",
        "energy",
        "patience",
        "helpfulness",
        "knowledge",
        "curiosity",
        "learning mindset",
        "quality focus",
        "customer focus",
        "teamwork",
        "adaptability",
        "flexibility",
        "efficiency",
        "organization",
        "reliability",
        "professionalism",
      ],
    },
  },

  gardener: {
    skills: {
      required: [
        "plant care",
        "watering",
        "pruning",
        "trimming",
        "weeding",
        "mulching",
        "fertilizing",
        "soil preparation",
        "planting",
        "transplanting",
        "lawn care",
        "mowing",
        "edging",
        "leaf removal",
        "garden maintenance",
        "landscape maintenance",
        "tool operation",
        "equipment maintenance",
        "seasonal care",
        "pest identification",
        "disease identification",
        "weather awareness",
        "safety procedures",
        "physical stamina",
        "outdoor work",
      ],
      preferred: [
        "plant identification",
        "botanical knowledge",
        "horticulture",
        "landscape design",
        "irrigation systems",
        "sprinkler systems",
        "drip irrigation",
        "water management",
        "organic gardening",
        "sustainable practices",
        "composting",
        "soil testing",
        "pH testing",
        "nutrient management",
        "integrated pest management",
        "beneficial insects",
        "companion planting",
        "seasonal planning",
        "garden design",
        "color coordination",
        "texture combinations",
      ],
      bonus: [
        "landscape architecture",
        "garden design",
        "permaculture",
        "xeriscaping",
        "native plants",
        "drought-resistant gardening",
        "rain gardens",
        "pollinator gardens",
        "vegetable gardening",
        "herb gardening",
        "fruit tree care",
        "greenhouse management",
        "nursery experience",
        "tree care",
        "arboriculture",
        "hardscaping",
        "stonework",
        "pathway installation",
        "water feature installation",
        "lighting installation",
        "equipment operation",
        "machinery operation",
      ],
    },
    experience: {
      keywords: [
        "gardening",
        "landscaping",
        "horticulture",
        "groundskeeping",
        "lawn care",
        "plant care",
        "landscape maintenance",
        "garden maintenance",
        "outdoor maintenance",
        "grounds maintenance",
        "nursery",
        "greenhouse",
        "botanical garden",
        "park maintenance",
        "golf course",
        "estate grounds",
        "commercial landscaping",
        "residential landscaping",
        "property maintenance",
      ],
      roles: [
        "gardener",
        "landscaper",
        "groundskeeper",
        "horticulturist",
        "lawn care specialist",
        "landscape technician",
        "garden maintenance worker",
        "grounds maintenance worker",
        "nursery worker",
        "greenhouse worker",
        "arborist",
        "tree care specialist",
        "irrigation technician",
        "landscape installer",
        "garden designer",
        "landscape designer",
      ],
      industries: [
        "landscaping",
        "lawn care",
        "horticulture",
        "nursery",
        "greenhouse",
        "botanical garden",
        "park services",
        "golf course",
        "resort",
        "hotel",
        "property management",
        "estate management",
        "commercial landscaping",
        "residential landscaping",
        "municipal services",
        "government",
      ],
    },
    training: {
      certifications: [
        "horticulture certification",
        "landscape certification",
        "pesticide applicator license",
        "irrigation certification",
        "arborist certification",
        "tree care certification",
        "lawn care certification",
        "organic gardening certification",
        "sustainable landscaping certification",
        "equipment operation certification",
        "safety certification",
        "first aid",
        "CPR",
      ],
      courses: [
        "horticulture",
        "landscape design",
        "plant science",
        "soil science",
        "entomology",
        "plant pathology",
        "irrigation systems",
        "pest management",
        "organic gardening",
        "sustainable landscaping",
        "equipment operation",
        "safety procedures",
        "business management",
      ],
      workshops: [
        "pruning workshop",
        "plant identification workshop",
        "soil management workshop",
        "pest management workshop",
        "irrigation workshop",
        "organic gardening workshop",
        "native plant workshop",
        "sustainable landscaping workshop",
        "equipment training workshop",
      ],
    },
    education: {
      preferred: [
        "horticulture",
        "landscape architecture",
        "botany",
        "plant science",
        "agriculture",
        "environmental science",
        "forestry",
        "turf management",
        "soil science",
        "entomology",
        "plant pathology",
        "sustainable agriculture",
        "organic farming",
        "permaculture design",
      ],
      relevant: [
        "horticulture degree",
        "landscape degree",
        "agriculture degree",
        "botany degree",
        "environmental science degree",
        "forestry degree",
        "gardening certification",
        "landscape certification",
      ],
    },
    personality: {
      traits: [
        "nature-loving",
        "outdoorsy",
        "patient",
        "observant",
        "detail-oriented",
        "nurturing",
        "caring",
        "responsible",
        "reliable",
        "hardworking",
        "physical",
        "strong",
        "enduring",
        "weather-tolerant",
        "seasonal-aware",
        "environmentally conscious",
        "sustainable-minded",
        "creative",
        "artistic",
        "aesthetic-minded",
        "problem-solving",
        "adaptable",
        "flexible",
      ],
      keywords: [
        "love of nature",
        "outdoor enthusiasm",
        "patience",
        "observation skills",
        "attention to detail",
        "nurturing nature",
        "caring attitude",
        "responsibility",
        "reliability",
        "work ethic",
        "physical fitness",
        "strength",
        "endurance",
        "weather tolerance",
        "seasonal awareness",
        "environmental consciousness",
        "sustainability mindset",
        "creativity",
        "artistic sense",
        "aesthetic appreciation",
        "problem solving",
        "adaptability",
        "flexibility",
      ],
    },
  },

  receptionist: {
    skills: {
      required: [
        "phone etiquette",
        "customer service",
        "communication",
        "active listening",
        "professional demeanor",
        "appointment scheduling",
        "calendar management",
        "visitor management",
        "greeting guests",
        "information provision",
        "message taking",
        "call routing",
        "multi-line phone system",
        "computer skills",
        "data entry",
        "filing",
        "record keeping",
        "office organization",
        "time management",
        "multitasking",
        "problem solving",
        "conflict resolution",
        "discretion",
      ],
      preferred: [
        "office software",
        "Microsoft Office",
        "scheduling software",
        "CRM systems",
        "database management",
        "email management",
        "correspondence",
        "document preparation",
        "report generation",
        "inventory management",
        "supply ordering",
        "vendor coordination",
        "meeting coordination",
        "travel arrangements",
        "expense reporting",
        "billing support",
        "payment processing",
        "insurance verification",
        "patient registration",
        "client intake",
        "confidentiality",
      ],
      bonus: [
        "multiple languages",
        "bilingual",
        "trilingual",
        "medical terminology",
        "legal terminology",
        "industry-specific knowledge",
        "specialized software",
        "advanced computer skills",
        "social media management",
        "marketing support",
        "event coordination",
        "training experience",
        "supervisory experience",
        "team coordination",
        "project management",
        "quality assurance",
        "compliance knowledge",
        "regulatory knowledge",
        "security procedures",
        "emergency procedures",
      ],
    },
    experience: {
      keywords: [
        "receptionist",
        "front desk",
        "customer service",
        "administrative",
        "office",
        "clerical",
        "secretary",
        "administrative assistant",
        "office assistant",
        "guest services",
        "client services",
        "patient services",
        "visitor services",
        "information desk",
        "help desk",
        "call center",
        "phone support",
        "customer support",
        "front office",
        "business office",
        "medical office",
      ],
      roles: [
        "receptionist",
        "front desk clerk",
        "administrative assistant",
        "office assistant",
        "customer service representative",
        "guest services associate",
        "client services coordinator",
        "patient services representative",
        "information specialist",
        "call center representative",
        "phone operator",
        "switchboard operator",
        "office coordinator",
        "administrative coordinator",
      ],
      industries: [
        "healthcare",
        "medical",
        "dental",
        "veterinary",
        "legal",
        "corporate",
        "professional services",
        "hospitality",
        "hotel",
        "real estate",
        "insurance",
        "financial services",
        "government",
        "education",
        "non-profit",
        "retail",
        "automotive",
        "construction",
        "manufacturing",
      ],
    },
    training: {
      certifications: [
        "customer service certification",
        "administrative certification",
        "office management certification",
        "computer skills certification",
        "Microsoft Office certification",
        "medical office certification",
        "HIPAA certification",
        "confidentiality training",
        "phone etiquette certification",
        "professional communication certification",
        "conflict resolution certification",
      ],
      courses: [
        "office administration",
        "business administration",
        "customer service",
        "communication skills",
        "computer applications",
        "office software",
        "medical office procedures",
        "legal office procedures",
        "business communication",
        "professional development",
        "time management",
        "organizational skills",
      ],
      workshops: [
        "customer service workshop",
        "communication workshop",
        "phone etiquette workshop",
        "conflict resolution workshop",
        "time management workshop",
        "organizational workshop",
        "computer skills workshop",
        "professional development workshop",
        "stress management workshop",
      ],
    },
    education: {
      preferred: [
        "business administration",
        "office administration",
        "communications",
        "customer service",
        "hospitality management",
        "healthcare administration",
        "medical office administration",
        "legal studies",
        "public relations",
        "marketing",
        "human resources",
        "psychology",
      ],
      relevant: [
        "business degree",
        "administrative certification",
        "office management certification",
        "customer service training",
        "communication degree",
        "hospitality degree",
        "healthcare administration",
      ],
    },
    personality: {
      traits: [
        "professional",
        "courteous",
        "friendly",
        "helpful",
        "patient",
        "calm",
        "organized",
        "detail-oriented",
        "reliable",
        "trustworthy",
        "discreet",
        "confidential",
        "articulate",
        "clear-speaking",
        "good listener",
        "empathetic",
        "understanding",
        "diplomatic",
        "tactful",
        "positive",
        "welcoming",
        "approachable",
        "efficient",
        "multitasking",
        "adaptable",
      ],
      keywords: [
        "professionalism",
        "courtesy",
        "friendliness",
        "helpfulness",
        "patience",
        "calmness",
        "organization",
        "attention to detail",
        "reliability",
        "trustworthiness",
        "discretion",
        "confidentiality",
        "articulation",
        "clear communication",
        "listening skills",
        "empathy",
        "understanding",
        "diplomacy",
        "tact",
        "positive attitude",
        "welcoming nature",
        "approachability",
        "efficiency",
        "multitasking ability",
        "adaptability",
      ],
    },
  },
}

export const SCORING_WEIGHTS: WeightedCriteria = {
  education: {
    // Doctoral level
    phd: 100,
    doctorate: 100,
    doctoral: 100,
    "ph.d": 100,
    "doctor of philosophy": 100,
    md: 100,
    "doctor of medicine": 100,
    jd: 100,
    "juris doctor": 100,
    edd: 100,

    // Masters level
    masters: 85,
    "master's": 85,
    mba: 90,
    "graduate degree": 85,
    ms: 85,
    ma: 85,
    mfa: 85,
    mpa: 85,
    mph: 85,
    msw: 85,
    med: 85,
    meng: 85,

    // Bachelors level
    bachelors: 70,
    "bachelor's": 70,
    undergraduate: 70,
    "college degree": 70,
    bs: 70,
    ba: 70,
    bfa: 70,
    bba: 70,
    bsc: 70,
    "four year degree": 70,

    // Associates level
    associates: 55,
    "associate's": 55,
    "community college": 50,
    "two year degree": 55,
    aa: 55,
    as: 55,
    aas: 55,
    "applied science": 55,

    // Vocational/Trade
    "trade school": 45,
    "vocational training": 45,
    "technical school": 45,
    "vocational school": 45,
    "certificate program": 40,
    "professional certificate": 45,
    "industry certification": 50,
    apprenticeship: 50,
    "trade certification": 45,

    // High school
    "high school": 30,
    ged: 30,
    diploma: 30,
    "secondary education": 30,
    hsed: 30,
    equivalency: 30,
    "some college": 40,
    "college coursework": 35,
  },

  experience: {
    // Senior level experience
    "20+ years": 100,
    "15-20 years": 95,
    "10-15 years": 90,
    "10+ years": 90,

    // Mid-level experience
    "8-10 years": 85,
    "5-8 years": 80,
    "5+ years": 75,
    "3-5 years": 70,

    // Junior level experience
    "2-3 years": 60,
    "1-2 years": 50,
    "1+ year": 45,
    "6 months - 1 year": 40,

    // Entry level
    "entry level": 30,
    "no experience": 20,
    "recent graduate": 35,
    "new graduate": 35,
    internship: 35,
    "co-op": 35,
    volunteer: 25,
    "part-time": 30,
    seasonal: 25,

    // Specialized experience
    management: 85,
    supervisory: 75,
    leadership: 80,
    training: 70,
    mentoring: 65,
  },

  skills: {
    required: 100, // Critical skills get full weight
    preferred: 75, // Important skills get good weight
    bonus: 50, // Nice-to-have skills get moderate weight
  },

  certifications: {
    // Professional licenses and certifications
    "professional license": 100,
    "state license": 95,
    "federal certification": 95,
    "industry certification": 90,
    "professional certification": 85,
    "board certification": 95,

    // Safety and compliance
    "safety certification": 85,
    "osha certification": 80,
    "hazmat certification": 85,
    "first aid": 70,
    cpr: 70,
    aed: 65,
    "emergency response": 75,

    // Technical certifications
    "technical certification": 80,
    "software certification": 75,
    "equipment certification": 70,
    "specialized training": 75,
    "advanced training": 80,
    "expert certification": 85,

    // General training
    "workshop completion": 60,
    "seminar attendance": 50,
    "online course": 50,
    "continuing education": 55,
    "professional development": 60,
    "basic training": 40,
  },
}

export const POSITION_SCORING_MULTIPLIERS = {
  "kitchen-helper": {
    education: 0.5, // Education less critical for entry-level kitchen work
    experience: 1.3, // Hands-on experience very important
    skills: 1.5, // Practical skills most important
    certifications: 1.1, // Food safety certs important
  },
  "server-waiter": {
    education: 0.7, // Some education helpful for communication
    experience: 1.4, // Customer service experience crucial
    skills: 1.3, // People skills and service skills key
    certifications: 0.9, // Some certs helpful but not critical
  },
  "house-keeping": {
    education: 0.4, // Minimal education requirements
    experience: 1.2, // Experience with cleaning important
    skills: 1.4, // Attention to detail and efficiency key
    certifications: 1.2, // Safety and cleaning certs valuable
  },
  cashier: {
    education: 0.8, // Basic math and communication skills
    experience: 1.1, // Some experience helpful
    skills: 1.3, // Accuracy and customer service key
    certifications: 1.0, // Standard importance
  },
  barista: {
    education: 0.6, // Some education helpful but not required
    experience: 1.2, // Coffee/service experience important
    skills: 1.4, // Coffee skills and customer service key
    certifications: 1.1, // Coffee certifications valuable
  },
  gardener: {
    education: 0.7, // Horticulture education helpful
    experience: 1.3, // Hands-on gardening experience crucial
    skills: 1.4, // Plant care and maintenance skills key
    certifications: 1.2, // Pesticide and safety certs important
  },
  receptionist: {
    education: 0.9, // Communication and office skills important
    experience: 1.1, // Office/customer service experience helpful
    skills: 1.2, // Communication and organizational skills key
    certifications: 1.0, // Standard importance
  },
}

export class SkillMatcher {
  static matchSkills(
    applicantText: string,
    positionSkills: string[],
    threshold = 0.65, // Lowered threshold for better matching
  ): {
    matches: string[]
    score: number
    confidence: number
  } {
    const text = applicantText.toLowerCase()
    const matches: string[] = []
    let totalConfidence = 0

    for (const positionSkill of positionSkills) {
      const skillLower = positionSkill.toLowerCase()
      let confidence = 0

      // Exact match (highest confidence)
      if (text.includes(skillLower)) {
        confidence = 1.0
      }
      // Partial word match
      else if (this.hasPartialMatch(text, skillLower)) {
        confidence = 0.9
      }
      // Fuzzy similarity match
      else {
        const similarity = this.calculateBestSimilarity(text, skillLower)
        if (similarity >= threshold) {
          confidence = similarity
        }
      }

      // Contextual bonus for skill combinations
      if (confidence > 0) {
        confidence = this.applyContextualBonus(text, skillLower, confidence)
        matches.push(positionSkill)
        totalConfidence += confidence
      }
    }

    const avgConfidence = matches.length > 0 ? totalConfidence / matches.length : 0
    const score = positionSkills.length > 0 ? matches.length / positionSkills.length : 0

    return { matches, score, confidence: avgConfidence }
  }

  private static hasPartialMatch(text: string, skill: string): boolean {
    const skillWords = skill.split(/\s+/)
    const textWords = text.split(/\s+/)

    // Check if most skill words appear in text
    const matchedWords = skillWords.filter((skillWord) =>
      textWords.some(
        (textWord) =>
          textWord.includes(skillWord) ||
          skillWord.includes(textWord) ||
          this.calculateSimilarity(textWord, skillWord) > 0.8,
      ),
    )

    return matchedWords.length >= Math.ceil(skillWords.length * 0.7)
  }

  private static calculateBestSimilarity(text: string, skill: string): number {
    const textWords = text.split(/\s+/)
    let bestSimilarity = 0

    // Check similarity against individual words and phrases
    for (let i = 0; i < textWords.length; i++) {
      for (let j = i; j < Math.min(i + skill.split(" ").length + 1, textWords.length); j++) {
        const phrase = textWords.slice(i, j + 1).join(" ")
        const similarity = this.calculateSimilarity(phrase, skill)
        bestSimilarity = Math.max(bestSimilarity, similarity)
      }
    }

    return bestSimilarity
  }

  private static applyContextualBonus(text: string, skill: string, baseConfidence: number): number {
    let bonus = 0

    // Bonus for skill appearing in context with related terms
    const contextKeywords = [
      "experience",
      "skilled",
      "proficient",
      "expert",
      "certified",
      "trained",
      "years",
      "background",
      "knowledge",
      "familiar",
      "competent",
      "qualified",
    ]

    const skillIndex = text.indexOf(skill)
    if (skillIndex !== -1) {
      const contextWindow = text.substring(
        Math.max(0, skillIndex - 50),
        Math.min(text.length, skillIndex + skill.length + 50),
      )

      const contextMatches = contextKeywords.filter((keyword) => contextWindow.includes(keyword)).length

      bonus = Math.min(0.2, contextMatches * 0.05) // Max 20% bonus
    }

    return Math.min(1.0, baseConfidence + bonus)
  }

  private static calculateSimilarity(str1: string, str2: string): number {
    const longer = str1.length > str2.length ? str1 : str2
    const shorter = str1.length > str2.length ? str2 : str1

    if (longer.length === 0) return 1.0

    const editDistance = this.levenshteinDistance(longer, shorter)
    return (longer.length - editDistance) / longer.length
  }

  private static levenshteinDistance(str1: string, str2: string): number {
    const matrix = []

    for (let i = 0; i <= str2.length; i++) {
      matrix[i] = [i]
    }

    for (let j = 0; j <= str1.length; j++) {
      matrix[0][j] = j
    }

    for (let i = 1; i <= str2.length; i++) {
      for (let j = 1; j <= str1.length; j++) {
        if (str2.charAt(i - 1) === str1.charAt(j - 1)) {
          matrix[i][j] = matrix[i - 1][j - 1]
        } else {
          matrix[i][j] = Math.min(matrix[i - 1][j - 1] + 1, matrix[i][j - 1] + 1, matrix[i - 1][j] + 1)
        }
      }
    }

    return matrix[str2.length][str1.length]
  }

  static matchExperience(
    experienceText: string,
    position: string,
  ): {
    relevantExperience: boolean
    matchedKeywords: string[]
    score: number
  } {
    const reference = POSITION_SKILLS_REFERENCE[position]
    if (!reference) return { relevantExperience: false, matchedKeywords: [], score: 0 }

    const text = experienceText.toLowerCase()
    const allKeywords = [
      ...reference.experience.keywords,
      ...reference.experience.roles,
      ...reference.experience.industries,
    ]

    const matchedKeywords = allKeywords.filter((keyword) => text.includes(keyword.toLowerCase()))

    const relevantExperience = matchedKeywords.length > 0
    const score = allKeywords.length > 0 ? matchedKeywords.length / allKeywords.length : 0

    return { relevantExperience, matchedKeywords, score }
  }

  static matchPersonality(
    resumeText: string,
    position: string,
  ): {
    matchedTraits: string[]
    score: number
  } {
    const reference = POSITION_SKILLS_REFERENCE[position]
    if (!reference) return { matchedTraits: [], score: 0 }

    const text = resumeText.toLowerCase()
    const allTraits = [...reference.personality.traits, ...reference.personality.keywords]

    const matchedTraits = allTraits.filter((trait) => text.includes(trait.toLowerCase()))

    const score = allTraits.length > 0 ? matchedTraits.length / allTraits.length : 0

    return { matchedTraits, score }
  }
}
